[package]
edition = "2021"
name = "create-fastify-api"
version = "0.0.0"
license = "MIT"

[lib]
crate-type = ["cdylib"]

[dependencies]
# Default enable napi4 feature, see https://nodejs.org/api/n-api.html#node-api-version-matrix
napi = { version = "2.12", default-features = false, features = ["napi4"] }
napi-derive = "2.12"
create-fastify-api = { path = ".." }

[build-dependencies]
napi-build = "2.0"
